export const componentRegistryData = [
  // Built-in Blocks
  {
    name: 'call-to-action',
    displayName: 'Call to Action',
    description: 'Engaging CTA section with rich text and action buttons',
    category: 'cta',
    source: 'builtin',
    blockType: 'cta',
    importPath: '@/blocks/CallToAction/Component',
    configImportPath: '@/blocks/CallToAction/config',
    isActive: true,
  },
  {
    name: 'content',
    displayName: 'Content',
    description: 'Flexible columns layout with rich text and optional links',
    category: 'content',
    source: 'builtin',
    blockType: 'content',
    importPath: '@/blocks/Content/Component',
    configImportPath: '@/blocks/Content/config',
    isActive: true,
  },
  {
    name: 'content-section',
    displayName: 'Content Section',
    description: 'Section with title and rich text content',
    category: 'content',
    source: 'builtin',
    blockType: 'contentsection',
    importPath: '@/blocks/ContentSection/Component',
    configImportPath: '@/blocks/ContentSection/config',
    isActive: true,
  },
  {
    name: 'feature-block',
    displayName: 'Feature Block',
    description: 'Showcase features with icons and descriptions',
    category: 'features',
    source: 'builtin',
    blockType: 'feature',
    importPath: '@/blocks/FeatureBlock/Component',
    configImportPath: '@/blocks/FeatureBlock/config',
    isActive: true,
  },
  {
    name: 'faq',
    displayName: 'FAQ',
    description: 'Accordion-style FAQ section',
    category: 'faq',
    source: 'builtin',
    blockType: 'faq',
    importPath: '@/blocks/FAQ/Component',
    configImportPath: '@/blocks/FAQ/config',
    isActive: true,
  },
  {
    name: 'form-block',
    displayName: 'Form Block',
    description: 'Contact forms with validation and submissions',
    category: 'form',
    source: 'builtin',
    blockType: 'formBlock',
    importPath: '@/blocks/Form/Component',
    configImportPath: '@/blocks/Form/config',
    isActive: true,
  },
  {
    name: 'media-block',
    displayName: 'Media Block',
    description: 'Image or video embedding',
    category: 'media',
    source: 'builtin',
    blockType: 'mediaBlock',
    importPath: '@/blocks/MediaBlock/Component',
    configImportPath: '@/blocks/MediaBlock/config',
    isActive: true,
  },
  {
    name: 'text-with-image',
    displayName: 'Text with Image',
    description: 'Side-by-side text and image layout',
    category: 'content',
    source: 'builtin',
    blockType: 'textWithImage',
    importPath: '@/blocks/TextWithImage/Component',
    configImportPath: '@/blocks/TextWithImage/config',
    isActive: true,
  },
  {
    name: 'process',
    displayName: 'Process',
    description: 'Step-by-step process display',
    category: 'process',
    source: 'builtin',
    blockType: 'process',
    importPath: '@/blocks/Process/Component',
    configImportPath: '@/blocks/Process/config',
    isActive: true,
  },
  {
    name: 'team-section',
    displayName: 'Team Section',
    description: 'Team members display with photos and bios',
    category: 'team',
    source: 'builtin',
    blockType: 'teamSection',
    importPath: '@/blocks/TeamSection/Component',
    configImportPath: '@/blocks/TeamSection/config',
    isActive: true,
  },
  {
    name: 'reviews',
    displayName: 'Reviews',
    description: 'Customer testimonials and reviews',
    category: 'testimonials',
    source: 'builtin',
    blockType: 'reviews',
    importPath: '@/blocks/Reviews/Component',
    configImportPath: '@/blocks/Reviews/config',
    isActive: true,
  },
  {
    name: 'image-carousel',
    displayName: 'Image Carousel',
    description: 'Image carousel/slider',
    category: 'carousel',
    source: 'builtin',
    blockType: 'imageCarousel',
    importPath: '@/blocks/ImageCarousel/Component',
    configImportPath: '@/blocks/ImageCarousel/config',
    isActive: true,
  },
  {
    name: 'cards-carousel',
    displayName: 'Cards Carousel',
    description: 'Carousel of content cards',
    category: 'carousel',
    source: 'builtin',
    blockType: 'cardsCarousel',
    importPath: '@/blocks/CardsCarouselBlock/Component',
    configImportPath: '@/blocks/CardsCarouselBlock/config',
    isActive: true,
  },
  {
    name: 'marquee',
    displayName: 'Marquee',
    description: 'Scrolling marquee text',
    category: 'other',
    source: 'builtin',
    blockType: 'marquee',
    importPath: '@/blocks/MarqueeBlock/Component',
    configImportPath: '@/blocks/MarqueeBlock/config',
    isActive: true,
  },
  {
    name: 'suitable-applications',
    displayName: 'Suitable Applications',
    description: 'List of applications or use cases',
    category: 'content',
    source: 'builtin',
    blockType: 'suitableapplications',
    importPath: '@/blocks/SuitableApplications/Component',
    configImportPath: '@/blocks/SuitableApplications/config',
    isActive: true,
  },
  {
    name: 'archive-block',
    displayName: 'Archive Block',
    description: 'Archive with filtering and pagination',
    category: 'other',
    source: 'builtin',
    blockType: 'archive',
    importPath: '@/blocks/ArchiveBlock/Component',
    configImportPath: '@/blocks/ArchiveBlock/config',
    isActive: true,
  },
  {
    name: 'banner',
    displayName: 'Banner',
    description: 'Info/Warning/Error/Success banners',
    category: 'other',
    source: 'builtin',
    blockType: 'banner',
    importPath: '@/blocks/Banner/Component',
    configImportPath: '@/blocks/Banner/config',
    isActive: false, // Check if this block exists
  },
  {
    name: 'code',
    displayName: 'Code',
    description: 'Code syntax highlighting block',
    category: 'other',
    source: 'builtin',
    blockType: 'code',
    importPath: '@/blocks/Code/Component',
    configImportPath: '@/blocks/Code/config',
    isActive: false, // Check if this block exists
  },
  {
    name: 'contact-cta',
    displayName: 'Contact CTA',
    description: 'Contact call-to-action section',
    category: 'cta',
    source: 'builtin',
    blockType: 'contactCTA',
    importPath: '@/blocks/ContactCTA/Component',
    configImportPath: '@/blocks/ContactCTA/config',
    isActive: false, // Check if this block exists
  },
  {
    name: 'section-with-image',
    displayName: 'Section with Image',
    description: 'Section with background image',
    category: 'content',
    source: 'builtin',
    blockType: 'sectionWithImage',
    importPath: '@/blocks/SectionWithImage/Component',
    configImportPath: '@/blocks/SectionWithImage/config',
    isActive: false, // Check if this block exists
  },
  {
    name: 'related-posts',
    displayName: 'Related Posts',
    description: 'Shows related blog post links',
    category: 'other',
    source: 'builtin',
    blockType: 'relatedPosts',
    importPath: '@/blocks/RelatedPosts/Component',
    configImportPath: '@/blocks/RelatedPosts/config',
    isActive: false, // Check if this block exists
  },
  {
    name: 'related-projects',
    displayName: 'Related Projects',
    description: 'Shows related project links',
    category: 'other',
    source: 'builtin',
    blockType: 'relatedProjects',
    importPath: '@/blocks/RelatedProjects/Component',
    configImportPath: '@/blocks/RelatedProjects/config',
    isActive: false, // Check if this block exists
  },

  // NPM Components
  {
    name: 'feature-card',
    displayName: 'Feature Card',
    description: 'Customizable feature card with icons and variants from @huce-digital',
    category: 'features',
    source: 'npm',
    blockType: 'featureCard',
    npmPackage: '@huce-digital/sample-block',
    importPath: '@huce-digital/sample-block',
    configImportPath: '@huce-digital/sample-block/config',
    isActive: true,
    defaultConfig: {
      heading: 'Feature Title',
      description: 'Feature description goes here',
      variant: 'default',
    },
  },
  {
    name: 'sample-button',
    displayName: 'Sample Button',
    description: 'Reusable button component from @huce-digital',
    category: 'other',
    source: 'npm',
    blockType: 'sampleButton',
    npmPackage: '@huce-digital/sample-button',
    importPath: '@huce-digital/sample-button',
    configImportPath: '@huce-digital/sample-button',
    isActive: true,
    defaultConfig: {
      label: 'Click me',
      variant: 'primary',
      size: 'medium',
    },
  },
]
