import { RequiredDataFromCollectionSlug } from "payload";

export const contactForm: RequiredDataFromCollectionSlug<"forms"> = {
  formVariant: "googleMaps",
  confirmationMessage: {
    root: {
      type: "root",
      children: [
        {
          type: "heading",
          children: [
            {
              type: "text",
              detail: 0,
              format: 0,
              mode: "normal",
              style: "",
              text: "The contact form has been submitted successfully.",
              version: 1,
            },
          ],
          direction: "ltr",
          format: "",
          indent: 0,
          tag: "h2",
          version: 1,
        },
      ],
      direction: "ltr",
      format: "",
      indent: 0,
      version: 1,
    },
  },
  confirmationType: "message",
  createdAt: "2023-01-12T21:47:41.374Z",
  emails: [
    {
      emailFrom: '"Elanto" \u003Cnoreply@elanto.com\u003E',
      emailTo: "{{email}}",
      message: {
        root: {
          type: "root",
          children: [
            {
              type: "paragraph",
              children: [
                {
                  type: "text",
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "Dear {{firstName}} {{lastName}},",
                  version: 1,
                },
              ],
              direction: "ltr",
              format: "",
              indent: 0,
              textFormat: 0,
              version: 1,
            },
            {
              type: "paragraph",
              children: [
                {
                  type: "text",
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "Thank you for your interest in our {{service}} services. We have received your message and will get back to you as soon as possible.",
                  version: 1,
                },
              ],
              direction: "ltr",
              format: "",
              indent: 0,
              textFormat: 0,
              version: 1,
            },
            {
              type: "paragraph",
              children: [
                {
                  type: "text",
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "Your message: {{message}}",
                  version: 1,
                },
              ],
              direction: "ltr",
              format: "",
              indent: 0,
              textFormat: 0,
              version: 1,
            },
            {
              type: "paragraph",
              children: [
                {
                  type: "text",
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "Best regards,\nThe Elanto Team",
                  version: 1,
                },
              ],
              direction: "ltr",
              format: "",
              indent: 0,
              textFormat: 0,
              version: 1,
            },
          ],
          direction: "ltr",
          format: "",
          indent: 0,
          version: 1,
        },
      },
      subject: "Thank you for your interest in Elanto services",
    },
    {
      emailFrom: '"Elanto Contact Form" \u003Cnoreply@elanto.com\u003E',
      emailTo: "your-email@example.com",
      subject: "New contact form submission from {{firstName}} {{lastName}}",
      message: {
        root: {
          type: "root",
          children: [
            {
              type: "paragraph",
              children: [
                {
                  type: "text",
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "You have received a new contact form submission:",
                  version: 1,
                },
              ],
              direction: "ltr",
              format: "",
              indent: 0,
              textFormat: 0,
              version: 1,
            },
            {
              type: "paragraph",
              children: [
                {
                  type: "text",
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "Name: {{firstName}} {{lastName}}\nEmail: {{email}}\nPhone: {{phone}}\nService: {{service}}\nSubject: {{subject}}\nMessage: {{message}}",
                  version: 1,
                },
              ],
              direction: "ltr",
              format: "",
              indent: 0,
              textFormat: 0,
              version: 1,
            },
          ],
          direction: "ltr",
          format: "",
          indent: 0,
          version: 1,
        },
      },
    },
  ],
  fields: [
    {
      name: "firstName",
      blockName: "firstName",
      blockType: "text",
      label: "First Name",
      required: true,
      width: 50,
    },
    {
      name: "lastName",
      blockName: "lastName",
      blockType: "text",
      label: "Last Name",
      required: true,
      width: 50,
    },
    {
      name: "email",
      blockName: "email",
      blockType: "email",
      label: "Email",
      required: true,
      width: 50,
    },
    {
      name: "phone",
      blockName: "phone",
      blockType: "text",
      label: "Phone Number",
      required: true,
      width: 50,
    },
    {
      name: "service",
      blockName: "service",
      blockType: "select",
      label: "Service",
      required: true,
      width: 100,
      options: [
        {
          label: "Schilderwerk",
          value: "schilderwerk",
        },
        {
          label: "Kitwerk",
          value: "kitwerk",
        },
        {
          label: "Glaswerk",
          value: "glaswerk",
        },
      ],
    },
    {
      name: "subject",
      blockName: "subject",
      blockType: "text",
      label: "Subject",
      required: true,
      width: 100,
    },
    {
      name: "message",
      blockName: "message",
      blockType: "textarea",
      label: "Message",
      required: true,
      width: 100,
    },
  ],
  redirect: undefined,
  submitButtonLabel: "Submit",
  title: "Contact Form",
  updatedAt: "2023-01-12T21:47:41.374Z",
};
