import type { Payload, PayloadRequest } from "payload";

/**
 * Generated seed file for TestProject
 * Auto-generated by Velen Website Builder
 */
export const seed = async ({
  payload,
  req,
}: {
  payload: Payload;
  req: PayloadRequest;
}): Promise<void> => {
  payload.logger.info("Seeding TestProject...");

  try {
    // Create home page
    const homePage = await payload.create({
      collection: 'pages',
      data: {
        title: "TestProject",
        slug: "/",
        layout: [
    {
      blockType: "featureCard",
      id: "block-0",
      heading: "Feature Title",
      description: "Feature description goes here",
      variant: "default"
    }
        ],
        _status: 'published',
      },
    });

    payload.logger.info(`✓ Created home page: ${homePage.id}`);

    // Update header global
    await payload.updateGlobal({
      slug: 'header',
      data: {
        navItems: [
        ],
      },
    });

    payload.logger.info("✓ Updated header navigation");

    // Update footer global
    await payload.updateGlobal({
      slug: 'footer',
      data: {
        navItems: [
          {
            link: {
              type: 'custom',
              label: 'Home',
              url: '/',
            }
          }
        ],
      },
    });

    payload.logger.info("✓ Updated footer");

    payload.logger.info("Seeded TestProject successfully! 🎉");
  } catch (error) {
    payload.logger.error("Seeding failed:", error);
    throw error;
  }
};
