interface SiteConfig {
  siteName: string
  slug: string
  theme: {
    primaryColor: string
    secondaryColor: string
    accentColor: string
    fontFamily: string
  }
  headerConfig: {
    headerType: string
    showSearch: boolean
    navItems: Array<{ label: string; url: string }>
  }
  heroConfig: {
    heroType: string
    heroData: any
  }
  selectedBlocks: Array<{
    blockType: string
    blockConfig: any
    order: number
  }>
}

export function generateSeedFileContent(siteConfig: SiteConfig): string {
  // Sort blocks by order
  const sortedBlocks = [...(siteConfig.selectedBlocks || [])].sort((a, b) => a.order - b.order)

  // Generate layout blocks for the home page
  const layoutBlocks = sortedBlocks.map((block, index) => {
    return `    {
      blockType: "${block.blockType}",
      id: "block-${index}",
      ${Object.entries(block.blockConfig || {})
        .map(([key, value]) => {
          if (typeof value === 'string') {
            return `${key}: "${value}"`
          } else if (typeof value === 'object' && value !== null) {
            return `${key}: ${JSON.stringify(value)}`
          }
          return `${key}: ${value}`
        })
        .join(',\n      ')}
    }`
  }).join(',\n')

  // Generate hero config
  const heroConfig = siteConfig.heroConfig?.heroType !== 'none' ? `
    hero: {
      type: "${siteConfig.heroConfig?.heroType || 'highImpact'}",
      ${siteConfig.heroConfig?.heroData?.title ? `richText: [{
        type: 'h1',
        children: [{ text: "${siteConfig.heroConfig.heroData.title}" }]
      }],` : ''}
      ${siteConfig.heroConfig?.heroData?.subtitle ? `description: "${siteConfig.heroConfig.heroData.subtitle}",` : ''}
      ${siteConfig.heroConfig?.heroData?.ctaText ? `links: [{
        link: {
          type: 'custom',
          url: "${siteConfig.heroConfig.heroData.ctaLink || '/'}",
          label: "${siteConfig.heroConfig.heroData.ctaText}",
        }
      }],` : ''}
    },` : ''

  // Generate nav items
  const navItems = (siteConfig.headerConfig?.navItems || []).map(item => `
      {
        link: {
          type: 'custom',
          label: "${item.label}",
          url: "${item.url}",
        }
      }`).join(',')

  return `import type { Payload, PayloadRequest } from "payload";

/**
 * Generated seed file for ${siteConfig.siteName}
 * Auto-generated by Velen Website Builder
 */
export const seed = async ({
  payload,
  req,
}: {
  payload: Payload;
  req: PayloadRequest;
}): Promise<void> => {
  payload.logger.info("Seeding ${siteConfig.siteName}...");

  try {
    // Create home page
    const homePage = await payload.create({
      collection: 'pages',
      data: {
        title: "${siteConfig.siteName}",
        slug: "/",${heroConfig}
        layout: [
${layoutBlocks}
        ],
        _status: 'published',
      },
    });

    payload.logger.info(\`✓ Created home page: \${homePage.id}\`);

    // Update header global
    await payload.updateGlobal({
      slug: 'header',
      data: {
        navItems: [${navItems}
        ],
      },
    });

    payload.logger.info("✓ Updated header navigation");

    // Update footer global
    await payload.updateGlobal({
      slug: 'footer',
      data: {
        navItems: [
          {
            link: {
              type: 'custom',
              label: 'Home',
              url: '/',
            }
          }
        ],
      },
    });

    payload.logger.info("✓ Updated footer");

    payload.logger.info("Seeded ${siteConfig.siteName} successfully! 🎉");
  } catch (error) {
    payload.logger.error("Seeding failed:", error);
    throw error;
  }
};
`
}
